# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import credential_driver_pb2 as credential__driver__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credential_driver_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredentialDriverStub:
    """Internal credential-driver contract used by the gateway.

    The gateway owns provider semantics and sandbox delivery. Credential drivers
    own backend-specific storage, deletion, authentication, and lookup for
    gateway-managed provider-secret handles. Secrets include injectable provider
    credentials and gateway-only refresh material.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCapabilities = channel.unary_unary(
                '/openshell.credentials.v1.CredentialDriver/GetCapabilities',
                request_serializer=credential__driver__pb2.GetCredentialDriverCapabilitiesRequest.SerializeToString,
                response_deserializer=credential__driver__pb2.GetCredentialDriverCapabilitiesResponse.FromString,
                _registered_method=True)
        self.StoreCredential = channel.unary_unary(
                '/openshell.credentials.v1.CredentialDriver/StoreCredential',
                request_serializer=credential__driver__pb2.StoreCredentialRequest.SerializeToString,
                response_deserializer=credential__driver__pb2.StoreCredentialResponse.FromString,
                _registered_method=True)
        self.DeleteCredential = channel.unary_unary(
                '/openshell.credentials.v1.CredentialDriver/DeleteCredential',
                request_serializer=credential__driver__pb2.DeleteCredentialRequest.SerializeToString,
                response_deserializer=credential__driver__pb2.DeleteCredentialResponse.FromString,
                _registered_method=True)
        self.ResolveCredentials = channel.unary_unary(
                '/openshell.credentials.v1.CredentialDriver/ResolveCredentials',
                request_serializer=credential__driver__pb2.ResolveCredentialsRequest.SerializeToString,
                response_deserializer=credential__driver__pb2.ResolveCredentialsResponse.FromString,
                _registered_method=True)
        self.ListCredentials = channel.unary_unary(
                '/openshell.credentials.v1.CredentialDriver/ListCredentials',
                request_serializer=credential__driver__pb2.ListCredentialsRequest.SerializeToString,
                response_deserializer=credential__driver__pb2.ListCredentialsResponse.FromString,
                _registered_method=True)


class CredentialDriverServicer:
    """Internal credential-driver contract used by the gateway.

    The gateway owns provider semantics and sandbox delivery. Credential drivers
    own backend-specific storage, deletion, authentication, and lookup for
    gateway-managed provider-secret handles. Secrets include injectable provider
    credentials and gateway-only refresh material.
    """

    def GetCapabilities(self, request, context):
        """Report driver identity and feature support.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreCredential(self, request, context):
        """Store or overwrite one gateway-managed provider secret and return an opaque handle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCredential(self, request, context):
        """Delete one provider credential handle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveCredentials(self, request, context):
        """Resolve a batch of credential handles into string secret values.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCredentials(self, request, context):
        """Optionally list discoverable credentials. Drivers may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialDriverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=credential__driver__pb2.GetCredentialDriverCapabilitiesRequest.FromString,
                    response_serializer=credential__driver__pb2.GetCredentialDriverCapabilitiesResponse.SerializeToString,
            ),
            'StoreCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreCredential,
                    request_deserializer=credential__driver__pb2.StoreCredentialRequest.FromString,
                    response_serializer=credential__driver__pb2.StoreCredentialResponse.SerializeToString,
            ),
            'DeleteCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCredential,
                    request_deserializer=credential__driver__pb2.DeleteCredentialRequest.FromString,
                    response_serializer=credential__driver__pb2.DeleteCredentialResponse.SerializeToString,
            ),
            'ResolveCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveCredentials,
                    request_deserializer=credential__driver__pb2.ResolveCredentialsRequest.FromString,
                    response_serializer=credential__driver__pb2.ResolveCredentialsResponse.SerializeToString,
            ),
            'ListCredentials': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCredentials,
                    request_deserializer=credential__driver__pb2.ListCredentialsRequest.FromString,
                    response_serializer=credential__driver__pb2.ListCredentialsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openshell.credentials.v1.CredentialDriver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openshell.credentials.v1.CredentialDriver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialDriver:
    """Internal credential-driver contract used by the gateway.

    The gateway owns provider semantics and sandbox delivery. Credential drivers
    own backend-specific storage, deletion, authentication, and lookup for
    gateway-managed provider-secret handles. Secrets include injectable provider
    credentials and gateway-only refresh material.
    """

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.credentials.v1.CredentialDriver/GetCapabilities',
            credential__driver__pb2.GetCredentialDriverCapabilitiesRequest.SerializeToString,
            credential__driver__pb2.GetCredentialDriverCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.credentials.v1.CredentialDriver/StoreCredential',
            credential__driver__pb2.StoreCredentialRequest.SerializeToString,
            credential__driver__pb2.StoreCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.credentials.v1.CredentialDriver/DeleteCredential',
            credential__driver__pb2.DeleteCredentialRequest.SerializeToString,
            credential__driver__pb2.DeleteCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.credentials.v1.CredentialDriver/ResolveCredentials',
            credential__driver__pb2.ResolveCredentialsRequest.SerializeToString,
            credential__driver__pb2.ResolveCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCredentials(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openshell.credentials.v1.CredentialDriver/ListCredentials',
            credential__driver__pb2.ListCredentialsRequest.SerializeToString,
            credential__driver__pb2.ListCredentialsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
