import { useCallback, useEffect, useState } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { api } from '@/lib/api';
import type {
  EscalationItem,
  EscalationResponse,
  EscalationStatus,
  EscalationTarget,
  CreateEscalationRequest,
  UpdateEscalationItemRequest,
} from '@/lib/api';
import { Icon } from '@/components/ui/Icon';
import { StatusDot } from '@/components/ui/StatusDot';
import { EmptyState } from '@/components/ui/EmptyState';

// ── constants ─────────────────────────────────────────────────────────────────

const STATUSES: EscalationStatus[] = ['new', 'ready', 'in-progress', 'done', 'blocked', 'skipped'];
const TARGETS: EscalationTarget[]  = ['claude-code', 'opencode', 'manual'];

const STATUS_COLOR: Record<string, string> = {
  new:          'var(--txt-2)',
  ready:        'var(--green)',
  'in-progress':'var(--live)',
  done:         'var(--green)',
  blocked:      'var(--red)',
  skipped:      'var(--txt-3)',
};

const TARGET_LABEL: Record<string, string> = {
  'claude-code': 'Claude Code',
  'opencode':    'OpenCode',
  'manual':      'Manual',
};

const PRIORITY_COLOR: Record<string, string> = {
  high:   'var(--red)',
  medium: 'var(--amber)',
  low:    'var(--txt-3)',
};

function statusDot(status: string): 'live' | 'amber' | 'green' | 'grey' | 'red' {
  if (status === 'ready')        return 'green';
  if (status === 'in-progress')  return 'live';
  if (status === 'blocked')      return 'red';
  if (status === 'done')         return 'green';
  if (status === 'skipped')      return 'grey';
  return 'grey';
}

// ── helpers ───────────────────────────────────────────────────────────────────

function fmtDate(iso: string | null): string {
  if (!iso) return '—';
  try {
    return new Date(iso).toLocaleString('en', {
      month: 'short', day: 'numeric', year: 'numeric',
      hour: '2-digit', minute: '2-digit', hour12: false,
    });
  } catch { return iso; }
}

function truncate(text: string | null, n = 80): string {
  if (!text) return '';
  return text.length > n ? text.slice(0, n).trimEnd() + '…' : text;
}

// ── handoff prompt ────────────────────────────────────────────────────────────

function generateHandoffPrompt(item: EscalationItem): string {
  const targetKey = (item.target ?? 'manual').toLowerCase();
  const label =
    targetKey === 'claude-code' ? 'Claude Code Handoff Prompt' :
    targetKey === 'opencode'    ? 'OpenCode Handoff Prompt'    :
                                  'Manual Handoff Prompt';

  const lines: string[] = [];
  lines.push(`# ${label}`);
  lines.push('');
  lines.push(`## Task`);
  lines.push('');
  lines.push(item.task);
  lines.push('');
  lines.push('## Details');
  lines.push('');
  lines.push(`Target: ${TARGET_LABEL[targetKey] ?? item.target ?? 'Manual'}`);
  if (item.priority) lines.push(`Priority: ${item.priority}`);
  if (item.source)   lines.push(`Source: ${item.source}`);
  if (item.path)     lines.push(`Path/Repo: ${item.path}`);
  if (item.notes)    lines.push(`Notes: ${item.notes}`);
  if (item.created)  lines.push(`Created: ${item.created}`);
  lines.push('');
  lines.push('## Your task');
  lines.push('');
  if (item.path) {
    lines.push('1. Inspect the relevant code or files at the path above.');
    lines.push('2. Summarize the current state of the task.');
    lines.push('3. Propose a safe implementation plan.');
    lines.push('4. Make changes only if explicitly instructed in this session.');
    lines.push('5. Do not delete files without confirmation.');
    lines.push('6. Report any commands or tests run.');
    lines.push('7. Provide a final summary and list remaining risks.');
  } else {
    lines.push('1. Summarize the current state of the task based on the context above.');
    lines.push('2. Propose a safe implementation plan.');
    lines.push('3. Make changes only if explicitly instructed in this session.');
    lines.push('4. Do not delete files without confirmation.');
    lines.push('5. Report any commands or tests run.');
    lines.push('6. Provide a final summary and list remaining risks.');
  }
  lines.push('');
  lines.push('---');
  lines.push('⚠️ This prompt was generated by Brain UI. It does not launch any processes automatically.');
  lines.push('Run it manually in ' + (TARGET_LABEL[targetKey] ?? 'your tool of choice') + '.');
  return lines.join('\n');
}

// ── confirm modal ─────────────────────────────────────────────────────────────

interface ConfirmState {
  item:      EscalationItem;
  newStatus: EscalationStatus;
}

function StatusConfirmModal({
  confirm,
  filePath,
  loading,
  error,
  onApply,
  onCancel,
}: {
  confirm:  ConfirmState;
  filePath: string;
  loading:  boolean;
  error:    string | null;
  onApply:  () => void;
  onCancel: () => void;
}) {
  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(2px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 1000,
      }}
      onClick={(e) => { if (e.target === e.currentTarget && !loading) onCancel(); }}
    >
      <div className="panel" style={{
        width: 460, padding: 'var(--s5)',
        display: 'flex', flexDirection: 'column', gap: 'var(--s4)',
        boxShadow: 'var(--shadow-pop)',
      }}>
        <div style={{ fontWeight: 700, fontSize: 14 }}>Update escalation status</div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: 'var(--s2)' }}>
          <div style={{ fontSize: 12.5, color: 'var(--txt-0)', fontWeight: 500 }}>
            {truncate(confirm.item.task, 80)}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 12 }}>
            <span style={{ color: STATUS_COLOR[confirm.item.status] ?? 'var(--txt-2)' }}>
              {confirm.item.status}
            </span>
            <Icon name="arrow-right" size={12} style={{ color: 'var(--txt-3)' }} />
            <span style={{ color: STATUS_COLOR[confirm.newStatus] ?? 'var(--txt-0)', fontWeight: 600 }}>
              {confirm.newStatus}
            </span>
          </div>
        </div>

        <div style={{
          fontSize: 11, color: 'var(--txt-2)',
          padding: 'var(--s2) var(--s3)',
          background: 'var(--surface-2)', borderRadius: 'var(--r2)',
          border: '1px solid var(--line)', display: 'flex', flexDirection: 'column', gap: 3,
        }}>
          <div className="mono" style={{ fontSize: 10.5 }}>{filePath}</div>
          <div style={{ color: 'var(--txt-3)' }}>
            A backup is created before every write. Only the status cell is modified.
          </div>
        </div>

        {error && (
          <div style={{
            fontSize: 11.5, color: 'var(--red)',
            padding: 'var(--s2) var(--s3)',
            background: 'var(--red-bg)', borderRadius: 'var(--r2)',
            border: '1px solid var(--red-line)',
          }}>
            {error}
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 'var(--s2)' }}>
          <button className="btn btn-sm btn-ghost" onClick={onCancel} disabled={loading}>
            Cancel
          </button>
          <button className="btn btn-sm btn-primary" onClick={onApply} disabled={loading}>
            {loading ? 'Saving…' : 'Apply'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── new item modal ────────────────────────────────────────────────────────────

const EMPTY_FORM: CreateEscalationRequest = {
  task: '', target: 'claude-code', priority: null, source: null, path: null, notes: null,
};

function NewEscalationModal({
  loading,
  error,
  onSubmit,
  onCancel,
}: {
  loading:  boolean;
  error:    string | null;
  onSubmit: (req: CreateEscalationRequest) => void;
  onCancel: () => void;
}) {
  const [form, setForm] = useState<CreateEscalationRequest>(EMPTY_FORM);

  const set = (k: keyof CreateEscalationRequest, v: string) =>
    setForm((f) => ({ ...f, [k]: v || null }));

  const inputStyle: React.CSSProperties = {
    background: 'var(--surface-2)',
    border: '1px solid var(--line)',
    borderRadius: 'var(--r2)',
    padding: '7px 10px',
    color: 'var(--txt-0)',
    fontSize: 12.5,
    fontFamily: 'var(--font-ui)',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontSize: 11, color: 'var(--txt-2)', fontWeight: 600,
    textTransform: 'uppercase', letterSpacing: '0.04em',
    marginBottom: 3, display: 'block',
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(2px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 1000, padding: 'var(--s4)',
      }}
      onClick={(e) => { if (e.target === e.currentTarget && !loading) onCancel(); }}
    >
      <div className="panel" style={{
        width: '100%', maxWidth: 540, padding: 'var(--s5)',
        display: 'flex', flexDirection: 'column', gap: 'var(--s4)',
        boxShadow: 'var(--shadow-pop)',
      }}>
        <div style={{ fontWeight: 700, fontSize: 14 }}>New Escalation</div>

        {/* task */}
        <div>
          <label style={labelStyle}>Task <span style={{ color: 'var(--red)' }}>*</span></label>
          <input
            style={inputStyle}
            placeholder="Describe the task to escalate…"
            value={form.task}
            onChange={(e) => setForm((f) => ({ ...f, task: e.target.value }))}
            autoFocus
          />
        </div>

        {/* target */}
        <div>
          <label style={labelStyle}>Target <span style={{ color: 'var(--red)' }}>*</span></label>
          <select
            style={{ ...inputStyle, cursor: 'pointer' }}
            value={form.target}
            onChange={(e) => setForm((f) => ({ ...f, target: e.target.value as EscalationTarget }))}
          >
            {TARGETS.map((t) => (
              <option key={t} value={t}>{TARGET_LABEL[t]}</option>
            ))}
          </select>
        </div>

        {/* priority */}
        <div>
          <label style={labelStyle}>Priority <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <select
            style={{ ...inputStyle, cursor: 'pointer' }}
            value={form.priority ?? ''}
            onChange={(e) => setForm((f) => ({ ...f, priority: e.target.value || null }))}
          >
            <option value="">— none —</option>
            <option value="high">high</option>
            <option value="medium">medium</option>
            <option value="low">low</option>
          </select>
        </div>

        {/* source */}
        <div>
          <label style={labelStyle}>Source <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <input
            style={inputStyle}
            placeholder="Where this task originates…"
            value={form.source ?? ''}
            onChange={(e) => set('source', e.target.value)}
          />
        </div>

        {/* path */}
        <div>
          <label style={labelStyle}>Path / Repo <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <input
            style={{ ...inputStyle, fontFamily: 'var(--font-mono)', fontSize: 12 }}
            placeholder="e.g. src/lib/api.ts or github.com/…"
            value={form.path ?? ''}
            onChange={(e) => set('path', e.target.value)}
          />
        </div>

        {/* notes */}
        <div>
          <label style={labelStyle}>Notes <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <textarea
            style={{ ...inputStyle, resize: 'vertical', minHeight: 72 }}
            placeholder="Any context or constraints for the escalated agent…"
            value={form.notes ?? ''}
            onChange={(e) => set('notes', e.target.value)}
          />
        </div>

        {/* safety notice */}
        <div style={{
          fontSize: 11, color: 'var(--txt-3)',
          padding: 'var(--s2) var(--s3)',
          background: 'var(--surface-2)', borderRadius: 'var(--r2)',
          border: '1px solid var(--line)',
        }}>
          This creates a queue item only. It does not launch Claude Code, OpenCode, or shell commands.
        </div>

        {error && (
          <div style={{
            fontSize: 11.5, color: 'var(--red)',
            padding: 'var(--s2) var(--s3)',
            background: 'var(--red-bg)', borderRadius: 'var(--r2)',
            border: '1px solid var(--red-line)',
          }}>
            {error}
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 'var(--s2)' }}>
          <button className="btn btn-sm btn-ghost" onClick={onCancel} disabled={loading}>
            Cancel
          </button>
          <button
            className="btn btn-sm btn-primary"
            onClick={() => onSubmit(form)}
            disabled={loading || !form.task.trim()}
          >
            {loading ? 'Adding…' : 'Add Escalation'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── edit item modal ───────────────────────────────────────────────────────────

function EditEscalationModal({
  item,
  loading,
  error,
  onSubmit,
  onCancel,
}: {
  item:     EscalationItem;
  loading:  boolean;
  error:    string | null;
  onSubmit: (req: UpdateEscalationItemRequest) => void;
  onCancel: () => void;
}) {
  const [form, setForm] = useState<UpdateEscalationItemRequest>({
    task:     item.task,
    target:   (item.target as EscalationTarget) ?? 'claude-code',
    priority: item.priority ?? null,
    source:   item.source   ?? null,
    path:     item.path     ?? null,
    notes:    item.notes    ?? null,
  });

  const set = (k: keyof UpdateEscalationItemRequest, v: string) =>
    setForm((f) => ({ ...f, [k]: v || null }));

  const inputStyle: React.CSSProperties = {
    background: 'var(--surface-2)',
    border: '1px solid var(--line)',
    borderRadius: 'var(--r2)',
    padding: '7px 10px',
    color: 'var(--txt-0)',
    fontSize: 12.5,
    fontFamily: 'var(--font-ui)',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  };

  const labelStyle: React.CSSProperties = {
    fontSize: 11, color: 'var(--txt-2)', fontWeight: 600,
    textTransform: 'uppercase', letterSpacing: '0.04em',
    marginBottom: 3, display: 'block',
  };

  return (
    <div
      style={{
        position: 'fixed', inset: 0,
        background: 'rgba(0,0,0,0.45)', backdropFilter: 'blur(2px)',
        display: 'flex', alignItems: 'center', justifyContent: 'center',
        zIndex: 1000, padding: 'var(--s4)',
      }}
      onClick={(e) => { if (e.target === e.currentTarget && !loading) onCancel(); }}
    >
      <div className="panel" style={{
        width: '100%', maxWidth: 540, padding: 'var(--s5)',
        display: 'flex', flexDirection: 'column', gap: 'var(--s4)',
        boxShadow: 'var(--shadow-pop)',
      }}>
        <div style={{ fontWeight: 700, fontSize: 14 }}>Edit Escalation</div>

        {/* status + created — read-only info */}
        <div style={{
          display: 'flex', gap: 'var(--s4)', fontSize: 11.5, color: 'var(--txt-2)',
          padding: 'var(--s2) var(--s3)',
          background: 'var(--surface-2)', borderRadius: 'var(--r2)',
          border: '1px solid var(--line)',
        }}>
          <span>
            Status: <strong style={{ color: STATUS_COLOR[item.status] ?? 'var(--txt-0)' }}>{item.status}</strong>
          </span>
          {item.created && <span>Created: <strong>{item.created}</strong></span>}
          <span style={{ marginLeft: 'auto', fontSize: 10.5, color: 'var(--txt-3)' }}>read-only fields not shown</span>
        </div>

        {/* task */}
        <div>
          <label style={labelStyle}>Task <span style={{ color: 'var(--red)' }}>*</span></label>
          <input
            style={inputStyle}
            value={form.task}
            onChange={(e) => setForm((f) => ({ ...f, task: e.target.value }))}
            autoFocus
          />
        </div>

        {/* target */}
        <div>
          <label style={labelStyle}>Target <span style={{ color: 'var(--red)' }}>*</span></label>
          <select
            style={{ ...inputStyle, cursor: 'pointer' }}
            value={form.target}
            onChange={(e) => setForm((f) => ({ ...f, target: e.target.value as EscalationTarget }))}
          >
            {TARGETS.map((t) => (
              <option key={t} value={t}>{TARGET_LABEL[t]}</option>
            ))}
          </select>
        </div>

        {/* priority */}
        <div>
          <label style={labelStyle}>Priority <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <select
            style={{ ...inputStyle, cursor: 'pointer' }}
            value={form.priority ?? ''}
            onChange={(e) => setForm((f) => ({ ...f, priority: e.target.value || null }))}
          >
            <option value="">— none —</option>
            <option value="high">high</option>
            <option value="medium">medium</option>
            <option value="low">low</option>
          </select>
        </div>

        {/* source */}
        <div>
          <label style={labelStyle}>Source <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <input
            style={inputStyle}
            placeholder="Where this task originates…"
            value={form.source ?? ''}
            onChange={(e) => set('source', e.target.value)}
          />
        </div>

        {/* path */}
        <div>
          <label style={labelStyle}>Path / Repo <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <input
            style={{ ...inputStyle, fontFamily: 'var(--font-mono)', fontSize: 12 }}
            placeholder="e.g. src/lib/api.ts or github.com/…"
            value={form.path ?? ''}
            onChange={(e) => set('path', e.target.value)}
          />
        </div>

        {/* notes */}
        <div>
          <label style={labelStyle}>Notes <span style={{ color: 'var(--txt-3)', fontWeight: 400 }}>optional</span></label>
          <textarea
            style={{ ...inputStyle, resize: 'vertical', minHeight: 72 }}
            placeholder="Any context or constraints…"
            value={form.notes ?? ''}
            onChange={(e) => set('notes', e.target.value)}
          />
        </div>

        {error && (
          <div style={{
            fontSize: 11.5, color: 'var(--red)',
            padding: 'var(--s2) var(--s3)',
            background: 'var(--red-bg)', borderRadius: 'var(--r2)',
            border: '1px solid var(--red-line)',
          }}>
            {error}
          </div>
        )}

        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 'var(--s2)' }}>
          <button className="btn btn-sm btn-ghost" onClick={onCancel} disabled={loading}>
            Cancel
          </button>
          <button
            className="btn btn-sm btn-primary"
            onClick={() => onSubmit(form)}
            disabled={loading || !form.task.trim()}
          >
            {loading ? 'Saving…' : 'Save Changes'}
          </button>
        </div>
      </div>
    </div>
  );
}

// ── item row ──────────────────────────────────────────────────────────────────

function EscalationRow({
  item,
  onStatusChange,
  onCopyPrompt,
  onEdit,
  copiedId,
}: {
  item:           EscalationItem;
  onStatusChange: (item: EscalationItem, s: EscalationStatus) => void;
  onCopyPrompt:   (item: EscalationItem) => void;
  onEdit:         (item: EscalationItem) => void;
  copiedId:       string | null;
}) {
  const copied = copiedId === item.id;

  return (
    <tr style={{ borderBottom: '1px solid var(--line-soft)' }}>
      {/* task */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top' }}>
        <div style={{ fontWeight: 500, fontSize: 12.5, color: 'var(--txt-0)', lineHeight: 1.4 }}>
          {item.task}
        </div>
        {item.notes && (
          <div style={{ fontSize: 10.5, color: 'var(--txt-3)', marginTop: 2, lineHeight: 1.4 }}>
            {truncate(item.notes, 100)}
          </div>
        )}
      </td>

      {/* target */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top', whiteSpace: 'nowrap' }}>
        <span style={{
          fontSize: 11, fontWeight: 600, color: 'var(--txt-0)',
          padding: '2px 6px', borderRadius: 'var(--r1)',
          background: 'var(--surface-2)', border: '1px solid var(--line)',
        }}>
          {TARGET_LABEL[(item.target ?? '').toLowerCase()] ?? item.target ?? '—'}
        </span>
      </td>

      {/* status */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top', whiteSpace: 'nowrap' }}>
        <select
          style={{
            background: 'transparent',
            border: 'none',
            color: STATUS_COLOR[item.status] ?? 'var(--txt-2)',
            fontSize: 11.5,
            fontWeight: 600,
            cursor: 'pointer',
            fontFamily: 'var(--font-ui)',
            padding: '2px 0',
          }}
          value={item.status}
          onChange={(e) => onStatusChange(item, e.target.value as EscalationStatus)}
        >
          {STATUSES.map((s) => (
            <option key={s} value={s} style={{ color: STATUS_COLOR[s] ?? 'inherit' }}>{s}</option>
          ))}
        </select>
      </td>

      {/* priority */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top', whiteSpace: 'nowrap' }}>
        {item.priority ? (
          <span style={{ fontSize: 11, fontWeight: 600, color: PRIORITY_COLOR[item.priority] ?? 'var(--txt-2)' }}>
            {item.priority}
          </span>
        ) : (
          <span style={{ fontSize: 11, color: 'var(--txt-3)' }}>—</span>
        )}
      </td>

      {/* source + path */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top' }}>
        {item.source && (
          <div style={{ fontSize: 11, color: 'var(--txt-2)' }}>{truncate(item.source, 40)}</div>
        )}
        {item.path && (
          <div className="mono" style={{ fontSize: 10.5, color: 'var(--txt-3)', marginTop: 2 }}>
            {truncate(item.path, 50)}
          </div>
        )}
        {!item.source && !item.path && (
          <span style={{ fontSize: 11, color: 'var(--txt-3)' }}>—</span>
        )}
      </td>

      {/* created */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top', whiteSpace: 'nowrap' }}>
        <span className="mono" style={{ fontSize: 10.5, color: 'var(--txt-3)' }}>
          {item.created ?? '—'}
        </span>
      </td>

      {/* actions */}
      <td style={{ padding: '8px 10px', verticalAlign: 'top', whiteSpace: 'nowrap' }}>
        <div style={{ display: 'flex', gap: 'var(--s1)', flexWrap: 'nowrap' }}>
          <button
            className="btn btn-sm btn-ghost"
            onClick={() => onEdit(item)}
            title="Edit escalation fields"
            style={{ fontSize: 11 }}
          >
            <Icon name="edit" size={12} />
            Edit
          </button>
          <button
            className="btn btn-sm"
            onClick={() => onCopyPrompt(item)}
            title="Copy handoff prompt to clipboard"
            style={{ fontSize: 11 }}
          >
            <Icon name="layers" size={12} />
            {copied ? 'Copied!' : 'Copy prompt'}
          </button>
        </div>
      </td>
    </tr>
  );
}

// ── main page ─────────────────────────────────────────────────────────────────

export function EscalationPage() {
  const showToast = useAppStore((s) => s.showToast);

  const [data, setData]         = useState<EscalationResponse | null>(null);
  const [loading, setLoading]   = useState(true);
  const [error, setError]       = useState<string | null>(null);

  const [creating, setCreating] = useState(false);

  const [filterStatus,   setFilterStatus]   = useState('');
  const [filterTarget,   setFilterTarget]   = useState('');
  const [filterPriority, setFilterPriority] = useState('');
  const [search,         setSearch]         = useState('');

  const [newOpen,      setNewOpen]      = useState(false);
  const [newLoading,   setNewLoading]   = useState(false);
  const [newError,     setNewError]     = useState<string | null>(null);

  const [confirm,        setConfirm]        = useState<ConfirmState | null>(null);
  const [confirmLoading, setConfirmLoading] = useState(false);
  const [confirmError,   setConfirmError]   = useState<string | null>(null);

  const [copiedId, setCopiedId] = useState<string | null>(null);

  const [editItem,    setEditItem]    = useState<EscalationItem | null>(null);
  const [editLoading, setEditLoading] = useState(false);
  const [editError,   setEditError]   = useState<string | null>(null);

  // ── load ──────────────────────────────────────────────────────────────────
  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const d = await api.getVaultEscalations();
      setData(d);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not reach backend.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  // ── create starter file ───────────────────────────────────────────────────
  const handleCreateFile = async () => {
    setCreating(true);
    try {
      const d = await api.createEscalationQueueFile();
      setData(d);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not create file.');
    } finally {
      setCreating(false);
    }
  };

  // ── add item ──────────────────────────────────────────────────────────────
  const handleNewSubmit = async (req: CreateEscalationRequest) => {
    if (!req.task.trim()) return;
    setNewLoading(true);
    setNewError(null);
    try {
      const d = await api.createEscalationItem(req);
      setData(d);
      setNewOpen(false);
    } catch (err) {
      setNewError(err instanceof Error ? err.message : 'Could not add escalation.');
    } finally {
      setNewLoading(false);
    }
  };

  // ── status change ─────────────────────────────────────────────────────────
  const handleStatusChange = (item: EscalationItem, newStatus: EscalationStatus) => {
    if (newStatus === item.status) return;
    setConfirm({ item, newStatus });
    setConfirmError(null);
  };

  const handleStatusApply = async () => {
    if (!confirm || !data) return;
    setConfirmLoading(true);
    setConfirmError(null);
    try {
      await api.updateEscalationStatus(confirm.item.id, confirm.newStatus);
      await load();
      setConfirm(null);
    } catch (err) {
      setConfirmError(err instanceof Error ? err.message : 'Update failed.');
    } finally {
      setConfirmLoading(false);
    }
  };

  // ── copy prompt ───────────────────────────────────────────────────────────
  // The package is built by the backend (PRD §29) so its fields are testable and
  // can pull real context. The local template stays as an offline fallback —
  // losing the ability to hand work off because the backend is down would be a
  // worse failure than a slightly thinner prompt.
  const handleCopyPrompt = async (item: EscalationItem) => {
    let prompt: string;
    try {
      const pkg = await api.buildHandoffPackage({
        itemId: item.id,
        task: item.task,
        target: item.target ?? undefined,
        repoPath: item.path ?? undefined,
      });
      prompt = pkg.prompt;
    } catch {
      prompt = generateHandoffPrompt(item);
    }
    try {
      await navigator.clipboard.writeText(prompt);
      setCopiedId(item.id);
      showToast('Handoff prompt copied. Run it yourself — this app never launches it.');
      setTimeout(() => setCopiedId(null), 2500);
    } catch {
      showToast('Could not copy — check browser permissions.');
    }
  };

  // ── edit item ─────────────────────────────────────────────────────────────
  const handleEditOpen = (item: EscalationItem) => {
    setEditItem(item);
    setEditError(null);
  };

  const handleEditSubmit = async (req: UpdateEscalationItemRequest) => {
    if (!editItem) return;
    setEditLoading(true);
    setEditError(null);
    try {
      await api.updateEscalationItem(editItem.id, req);
      await load();
      setEditItem(null);
    } catch (err) {
      setEditError(err instanceof Error ? err.message : 'Update failed.');
    } finally {
      setEditLoading(false);
    }
  };

  // ── filter ────────────────────────────────────────────────────────────────
  const items = (data?.items ?? []).filter((it) => {
    if (filterStatus   && it.status   !== filterStatus)                    return false;
    if (filterTarget   && (it.target ?? '') !== filterTarget)              return false;
    if (filterPriority && (it.priority ?? '') !== filterPriority)          return false;
    if (search) {
      const q = search.toLowerCase();
      const haystack = [it.task, it.notes, it.source, it.path, it.created]
        .filter(Boolean).join(' ').toLowerCase();
      if (!haystack.includes(q)) return false;
    }
    return true;
  });

  const activeCount = (data?.items ?? []).filter(
    (it) => ['new', 'ready', 'in-progress', 'blocked'].includes(it.status)
  ).length;

  // ── render ────────────────────────────────────────────────────────────────

  const selectStyle: React.CSSProperties = {
    background: 'var(--surface-2)',
    border: '1px solid var(--line)',
    borderRadius: 'var(--r2)',
    padding: '6px 8px',
    color: 'var(--txt-0)',
    fontSize: 12,
    fontFamily: 'var(--font-ui)',
    cursor: 'pointer',
    outline: 'none',
  };

  return (
    <div style={{ maxWidth: 1200, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 'var(--s5)' }}>

      {/* ── header ── */}
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: 'var(--s4)', flexWrap: 'wrap' }}>
        <div>
          <div className="eyebrow" style={{ marginBottom: 4 }}>Control / Escalation</div>
          <h1 style={{ margin: 0, fontSize: 22, fontWeight: 600, letterSpacing: '-0.015em', color: 'var(--txt-0)' }}>
            Escalation Queue
          </h1>
          <div style={{ fontSize: 13, color: 'var(--txt-2)', marginTop: 3 }}>
            Tasks too complex for the local agent — queue for Claude Code or OpenCode
          </div>
        </div>
        <div style={{ display: 'flex', gap: 'var(--s2)' }}>
          <button className="btn btn-sm btn-ghost" onClick={load} disabled={loading} title="Refresh">
            <Icon name="sync" size={13} />{loading ? 'Loading…' : 'Refresh'}
          </button>
          {data?.exists && (
            <button className="btn btn-primary" onClick={() => { setNewOpen(true); setNewError(null); }}>
              <Icon name="plus" size={14} /> New Escalation
            </button>
          )}
        </div>
      </div>

      {/* ── meta row ── */}
      {data && (
        <div style={{ display: 'flex', gap: 'var(--s4)', flexWrap: 'wrap', alignItems: 'center', fontSize: 11.5, color: 'var(--txt-2)' }}>
          <span className="mono" style={{ color: 'var(--txt-3)' }}>{data.path}</span>
          {data.lastModified && <span>Modified {fmtDate(data.lastModified)}</span>}
          <span><strong style={{ color: 'var(--txt-0)' }}>{data.items.length}</strong> item{data.items.length === 1 ? '' : 's'}</span>
          {activeCount > 0 && (
            <span style={{ color: 'var(--violet)', fontWeight: 600 }}>{activeCount} active</span>
          )}
          <span style={{ color: 'var(--txt-3)' }}>{data.parseMode}</span>
        </div>
      )}

      {/* ── error ── */}
      {error && !loading && (
        <div style={{
          padding: '10px 14px', background: 'var(--surface-2)',
          border: '1px solid var(--red)', borderRadius: 'var(--r2)',
          fontSize: 12, color: 'var(--txt-1)', display: 'flex', alignItems: 'center', gap: 8,
        }}>
          <StatusDot tone="red" />
          <span>{error}</span>
          <button className="btn btn-sm btn-ghost" style={{ marginLeft: 'auto' }} onClick={load}>Retry</button>
        </div>
      )}

      {/* ── loading ── */}
      {loading && (
        <div style={{ color: 'var(--txt-3)', fontSize: 12, padding: 'var(--s4) 0' }}>Loading…</div>
      )}

      {/* ── missing state ── */}
      {!loading && !error && data && !data.exists && (
        <div className="panel panel-pad">
          <EmptyState
            icon="layers"
            title="No escalation queue found"
            desc={`Expected ${data.path}`}
          />
          <div style={{ display: 'flex', justifyContent: 'center', marginTop: 'var(--s4)' }}>
            <button className="btn btn-primary" onClick={handleCreateFile} disabled={creating}>
              <Icon name="plus" size={14} />
              {creating ? 'Creating…' : 'Create escalation queue'}
            </button>
          </div>
        </div>
      )}

      {/* ── preview-only fallback ── */}
      {!loading && !error && data?.exists && data.parseMode !== 'markdown-table' && data.items.length === 0 && (
        <div className="panel panel-pad">
          <div style={{ marginBottom: 'var(--s3)', fontSize: 12.5, fontWeight: 500, color: 'var(--txt-1)' }}>
            Escalation queue could not be parsed as a Markdown table.
          </div>
          {data.preview && (
            <pre className="mono" style={{
              fontSize: 10.5, color: 'var(--txt-2)', overflow: 'auto',
              maxHeight: 200, background: 'var(--surface-2)',
              padding: 'var(--s3)', borderRadius: 'var(--r2)',
              border: '1px solid var(--line)',
            }}>
              {data.preview}
            </pre>
          )}
        </div>
      )}

      {/* ── filter bar ── */}
      {!loading && data?.exists && data.parseMode === 'markdown-table' && (
        <div style={{ display: 'flex', gap: 'var(--s2)', flexWrap: 'wrap', alignItems: 'center' }}>
          <input
            style={{
              ...selectStyle,
              minWidth: 200,
              background: 'var(--surface-2)', border: '1px solid var(--line)',
              borderRadius: 'var(--r2)', padding: '6px 10px',
              color: 'var(--txt-0)', fontSize: 12, fontFamily: 'var(--font-ui)', outline: 'none',
            }}
            placeholder="Search task, notes, path…"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
          />
          <select style={selectStyle} value={filterStatus} onChange={(e) => setFilterStatus(e.target.value)}>
            <option value="">All statuses</option>
            {STATUSES.map((s) => <option key={s} value={s}>{s}</option>)}
          </select>
          <select style={selectStyle} value={filterTarget} onChange={(e) => setFilterTarget(e.target.value)}>
            <option value="">All targets</option>
            {TARGETS.map((t) => <option key={t} value={t}>{TARGET_LABEL[t]}</option>)}
          </select>
          <select style={selectStyle} value={filterPriority} onChange={(e) => setFilterPriority(e.target.value)}>
            <option value="">All priorities</option>
            <option value="high">high</option>
            <option value="medium">medium</option>
            <option value="low">low</option>
          </select>
          {(filterStatus || filterTarget || filterPriority || search) && (
            <button className="btn btn-sm btn-ghost" onClick={() => {
              setFilterStatus(''); setFilterTarget(''); setFilterPriority(''); setSearch('');
            }}>
              Clear
            </button>
          )}
          <span style={{ marginLeft: 'auto', fontSize: 11.5, color: 'var(--txt-3)' }}>
            {items.length} / {data.items.length} item{data.items.length === 1 ? '' : 's'}
          </span>
        </div>
      )}

      {/* ── items table ── */}
      {!loading && data?.exists && data.parseMode === 'markdown-table' && (
        <div className="panel" style={{ overflow: 'auto' }}>
          {items.length === 0 ? (
            <div style={{ padding: 'var(--s5)', textAlign: 'center', color: 'var(--txt-3)', fontSize: 12.5 }}>
              {data.items.length === 0
                ? 'No escalation items yet. Use "New Escalation" to add one.'
                : 'No items match the current filters.'}
            </div>
          ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 12 }}>
              <thead>
                <tr style={{ borderBottom: '1px solid var(--line)' }}>
                  {['Task', 'Target', 'Status', 'Priority', 'Source / Path', 'Created', 'Actions'].map((col) => (
                    <th key={col} style={{
                      padding: '8px 10px', textAlign: 'left',
                      fontSize: 10.5, fontWeight: 600, color: 'var(--txt-2)',
                      textTransform: 'uppercase', letterSpacing: '0.05em',
                      whiteSpace: 'nowrap',
                    }}>
                      {col}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {items.map((item) => (
                  <EscalationRow
                    key={item.id}
                    item={item}
                    onStatusChange={handleStatusChange}
                    onCopyPrompt={handleCopyPrompt}
                    onEdit={handleEditOpen}
                    copiedId={copiedId}
                  />
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* ── safety notice ── */}
      <div style={{
        fontSize: 11, color: 'var(--txt-3)',
        padding: 'var(--s2) var(--s3)',
        background: 'var(--surface-2)', borderRadius: 'var(--r2)',
        border: '1px solid var(--line)', display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <Icon name="shield" size={12} />
        Brain UI does not launch Claude Code, OpenCode, or shell commands. Copy the handoff prompt and run it manually.
      </div>

      {/* ── modals ── */}
      {confirm && (
        <StatusConfirmModal
          confirm={confirm}
          filePath={data?.path ?? ''}
          loading={confirmLoading}
          error={confirmError}
          onApply={handleStatusApply}
          onCancel={() => { setConfirm(null); setConfirmError(null); }}
        />
      )}

      {newOpen && (
        <NewEscalationModal
          loading={newLoading}
          error={newError}
          onSubmit={handleNewSubmit}
          onCancel={() => { setNewOpen(false); setNewError(null); }}
        />
      )}

      {editItem && (
        <EditEscalationModal
          item={editItem}
          loading={editLoading}
          error={editError}
          onSubmit={handleEditSubmit}
          onCancel={() => { setEditItem(null); setEditError(null); }}
        />
      )}
    </div>
  );
}
