/**
 * Projects — PRD §20.
 *
 * Was a read-only card list plus "New Project". The §20 actions are now present,
 * split by what they can honestly do:
 *   * brain scaffolds run through the allowlisted wrapper;
 *   * agent handoffs COPY a command — this app never launches Claude Code or
 *     OpenCode, and §29 is explicit that it should not try;
 *   * everything else navigates to the page that already owns that workflow.
 */
import { useCallback, useEffect, useState } from 'react';
import { useAppStore } from '@/store/useAppStore';
import { api } from '@/lib/api';
import type { VaultProject, GitHubCommit } from '@/lib/api';
import { EntityListPage } from '@/components/entities/EntityListPage';
import type { EntityAction } from '@/components/entities/EntityCard';

function closeoutPrompt(p: VaultProject): string {
  return [
    `# Project closeout — ${p.name}`,
    '',
    '## Context',
    `Wiki note: ${p.wikiPath ?? '(none)'}`,
    `Raw folder: ${p.rawPath ?? '(none)'}`,
    `Repo: ${p.repoPath ?? '(not recorded in frontmatter)'}`,
    p.githubUrl ? `GitHub: ${p.githubUrl}` : null,
    '',
    '## Your task',
    '1. Inspect the repo and the raw folder above.',
    '2. Summarize what was built, the decisions made, and what remains.',
    '3. Write a closeout suitable for the wiki note.',
    '4. Propose resume-pipeline bullets with concrete evidence.',
    '5. Do not delete anything. Report every command you run.',
    '',
    '---',
    'Generated by Brain UI. It does not launch this for you — run it yourself.',
  ].filter(Boolean).join('\n');
}

/** "owner/repo" from a GitHub URL, or null if this note has none. */
function repoSlug(url: string | null): string | null {
  if (!url) return null;
  const match = url.match(/github\.com\/([^/]+\/[^/#?]+)/i);
  return match ? match[1].replace(/\.git$/, '') : null;
}

export function ProjectsPage() {
  const navigate = useAppStore((s) => s.navigate);
  const showToast = useAppStore((s) => s.showToast);
  const runBrainCommand = useAppStore((s) => s.runBrainCommand);

  const [commits, setCommits] = useState<Record<string, GitHubCommit[]>>({});
  const [githubReady, setGithubReady] = useState(false);

  const load = useCallback(async () => (await api.getVaultProjects()).projects, []);

  useEffect(() => {
    api.githubStatus()
      .then((s) => setGithubReady(s.configured))
      .catch(() => setGithubReady(false));
  }, []);

  const loadCommits = useCallback(async (project: VaultProject) => {
    const slug = repoSlug(project.githubUrl);
    if (!slug) { showToast('No github_url in this note’s frontmatter.'); return; }
    try {
      const res = await api.githubCommits(slug, 5);
      setCommits((c) => ({ ...c, [project.id]: res.commits }));
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Could not read commits.');
    }
  }, [showToast]);

  const actionsFor = useCallback((p: VaultProject): EntityAction[] => {
    const actions: EntityAction[] = [
      { label: 'Closeout prompt', copy: closeoutPrompt(p),
        title: 'Copy a Claude Code / OpenCode handoff for this project' },
      { label: 'Run closeout', title: 'Runs `brain project-closeout` for this project',
        onClick: () => runBrainCommand('project-closeout', { name: p.name }) },
      { label: 'Repo scaffold', title: 'Runs `brain new-repo-scaffold`',
        onClick: () => runBrainCommand('new-repo-scaffold', { repo: p.repoPath || p.name, name: p.name }) },
      { label: 'Upload source', title: 'Route files through the Raw Inbox', onClick: () => navigate('inbox') },
      { label: 'Research', title: 'Start a time-boxed research session', onClick: () => navigate('research') },
      { label: 'Consolidate', title: 'Bring AI chat work into the vault', onClick: () => navigate('consolidate') },
      { label: 'Escalate', title: 'Add to the escalation queue', onClick: () => navigate('escalation') },
      { label: 'Resume row', title: 'Track this as resume evidence', onClick: () => navigate('resume') },
    ];
    if (githubReady && repoSlug(p.githubUrl)) {
      actions.splice(1, 0, {
        label: 'Commits', title: 'Read recent commits (read-only)',
        onClick: () => loadCommits(p),
      });
    }
    return actions;
  }, [githubReady, loadCommits, navigate, runBrainCommand]);

  return (
    <EntityListPage<VaultProject>
      title="Projects"
      kind="project"
      pathHint="wiki/projects/ · raw/projects/"
      icon="cube"
      newLabel="New Project"
      emptyTitle="No projects found"
      emptyDesc="No .md files in wiki/projects/ and no folders in raw/projects/. Create a project or route project files from the Raw Inbox."
      safetyNote={
        <>
          Scaffold and closeout actions run allowlisted <span className="mono">brain</span> commands.
          Agent handoffs are <strong>copied for you to run</strong> — this app never launches Claude
          Code or OpenCode.
        </>
      }
      load={load}
      actionsFor={actionsFor}
      create={{
        note: "Creates the project using `brain new-project <name>`. Add repo and link metadata to the note's frontmatter afterwards.",
        fields: [{ key: 'name', label: 'Name', placeholder: 'Project name', required: true }],
        submit: (values) => api.createProject({ name: values.name.trim() }),
      }}
      renderExtra={(p) => {
        const rows = commits[p.id];
        if (!rows) return null;
        return (
          <div className="panel panel-pad" style={{ padding: 'var(--s3)' }}>
            <div className="eyebrow" style={{ marginBottom: 4 }}>Recent commits · untrusted content</div>
            {rows.length === 0 ? (
              <div style={{ fontSize: 10.5, color: 'var(--txt-3)' }}>No commits returned.</div>
            ) : rows.map((c) => (
              <div key={c.sha} style={{ fontSize: 10.5, color: 'var(--txt-2)', display: 'flex', gap: 6 }}>
                <span className="mono" style={{ color: 'var(--txt-3)' }}>{c.sha.slice(0, 7)}</span>
                <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                  {c.message.split('\n')[0]}
                </span>
              </div>
            ))}
          </div>
        );
      }}
    />
  );
}
