"""
Local conversation history for the Brain UI local agent.

One JSON file per conversation under backend/data/conversations/<uuid>.json.

Safety rules:
- IDs are always UUID4s generated by the backend.
- User-supplied IDs are never used as filenames directly.
- All resolved paths are validated to be inside CONVERSATIONS_DIR.
- No vault writes occur here.
- System prompt is never stored as a visible message.
- Only the last CONTEXT_WINDOW_MESSAGES (default 10) user/assistant messages
  are forwarded to the model as context (see agent.py, main.py). System prompt
  is never included in this window.
"""

import json
import logging
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

CONVERSATIONS_DIR: Path = Path(__file__).parent.parent / "data" / "conversations"

_lock = threading.Lock()


# ── helpers ───────────────────────────────────────────────────────────────────

def _ensure_dir() -> None:
    CONVERSATIONS_DIR.mkdir(parents=True, exist_ok=True)


def _now_iso() -> str:
    return datetime.now(tz=timezone.utc).isoformat(timespec="milliseconds")


def _safe_path(conversation_id: str) -> Path:
    """
    Return the .json path for conversation_id after verifying it stays inside
    CONVERSATIONS_DIR. Raises ValueError on any traversal attempt.
    """
    _ensure_dir()
    # Reject anything with path separators or parent-traversal components.
    if "/" in conversation_id or "\\" in conversation_id or ".." in conversation_id:
        raise ValueError(f"Invalid conversation id: '{conversation_id}'")
    resolved = (CONVERSATIONS_DIR / f"{conversation_id}.json").resolve()
    root     = str(CONVERSATIONS_DIR.resolve())
    r_str    = str(resolved)
    if not (r_str == root or r_str.startswith(root + "/") or r_str.startswith(root + "\\")):
        raise ValueError(f"Invalid conversation id: '{conversation_id}'")
    return resolved


def _read(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception as exc:
        logger.error("Could not read %s: %s", path, exc)
        return None


def _write(path: Path, data: dict) -> None:
    path.write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )


# ── public API ────────────────────────────────────────────────────────────────

def create_conversation(title: Optional[str] = None) -> dict:
    with _lock:
        _ensure_dir()
        cid = str(uuid.uuid4())
        now = _now_iso()
        data = {
            "id":        cid,
            "title":     (title or "New conversation").strip() or "New conversation",
            "createdAt": now,
            "updatedAt": now,
            "messages":  [],
        }
        _write(_safe_path(cid), data)
        logger.info("Created conversation %s", cid)
        return data


def list_conversations() -> list[dict]:
    """Return summaries (no messages) sorted by updatedAt desc."""
    _ensure_dir()
    summaries = []
    for p in CONVERSATIONS_DIR.glob("*.json"):
        try:
            raw = json.loads(p.read_text(encoding="utf-8"))
            summaries.append({
                "id":           raw["id"],
                "title":        raw.get("title", "Untitled"),
                "createdAt":    raw.get("createdAt", ""),
                "updatedAt":    raw.get("updatedAt", ""),
                "messageCount": len(raw.get("messages", [])),
            })
        except Exception as exc:
            logger.warning("Skipping corrupt conversation file %s: %s", p.name, exc)
    summaries.sort(key=lambda r: r.get("updatedAt", ""), reverse=True)
    return summaries


def get_conversation(conversation_id: str) -> Optional[dict]:
    """Load the full conversation. Returns None if not found."""
    try:
        path = _safe_path(conversation_id)
    except ValueError:
        return None
    if not path.exists():
        return None
    return _read(path)


def delete_conversation(conversation_id: str) -> bool:
    """Delete a conversation file. Returns True if deleted, False if not found."""
    try:
        path = _safe_path(conversation_id)
    except ValueError:
        return False
    with _lock:
        if not path.exists():
            return False
        path.unlink()
        logger.info("Deleted conversation %s", conversation_id)
        return True


def save_chat_turn(
    conversation_id: str,
    user_message:    str,
    assistant_content: str,
    provider:        str,
    model:           str,
    duration_ms:     float,
) -> Optional[dict]:
    """
    Append a user + assistant message pair to the conversation.

    - Auto-titles from the first user message (first 50 chars).
    - The system prompt is NEVER stored here.
    - Returns the updated conversation dict, or None if not found.
    """
    try:
        path = _safe_path(conversation_id)
    except ValueError:
        return None

    with _lock:
        if not path.exists():
            return None

        data = _read(path)
        if data is None:
            return None

        now = _now_iso()

        # Auto-title from first user message
        if (
            not data["messages"]
            and data.get("title") in (None, "", "New conversation")
        ):
            data["title"] = user_message[:50].strip() or "New conversation"

        data["messages"].append({
            "id":        str(uuid.uuid4()),
            "role":      "user",
            "content":   user_message,
            "createdAt": now,
            "provider":  None,
            "model":     None,
            "durationMs": None,
        })
        data["messages"].append({
            "id":        str(uuid.uuid4()),
            "role":      "assistant",
            "content":   assistant_content,
            "createdAt": now,
            "provider":  provider,
            "model":     model,
            "durationMs": duration_ms,
        })
        data["updatedAt"] = now

        _write(path, data)
        return data
